package autosched2;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;


public class MainTabbedUI extends javax.swing.JFrame {       

    private SubjectConfigPanel subjectConfigPanel1stSem;
    private SubjectConfigPanel1 subjectConfigPanel2ndSem;
    private AutoSchedulePanel autoSchedulePanel;

    public MainTabbedUI(String username) {
        javax.swing.UIManager.put("TabbedPane.font", new Font("Segoe UI", Font.PLAIN, 18));
        initComponents();
        setLayout(new BorderLayout());
        JPanel topPanel = new JPanel(new BorderLayout());
        topPanel.setBackground(new Color(255, 235, 245));
        JLabel welcomeLabel = new JLabel("Welcome, " + username);
        welcomeLabel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 0));
        welcomeLabel.setFont((new Font("Segoe UI", Font.BOLD, 16)));
        topPanel.add(welcomeLabel, BorderLayout.WEST);
        JButton logoutBtn = new JButton("Logout");
        logoutBtn.setBackground(new Color(255, 192, 203));
        logoutBtn.setFont((new Font("Segoe UI", Font.BOLD, 16)));
        logoutBtn.setForeground(Color.BLACK);
        logoutBtn.addActionListener(e -> {
            dispose();
            new LoginFrame();
        });
        JPanel logoutPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        logoutPanel.setOpaque(false);
        logoutPanel.add(logoutBtn);
        topPanel.add(logoutPanel, BorderLayout.EAST);



        add(topPanel, BorderLayout.NORTH);
        add(mainTabs);


        
        Font uiFont = new Font("Segoe UI", Font.PLAIN, 18);
        UIManager.put("Label.font", uiFont);
        UIManager.put("Button.font", uiFont);
        UIManager.put("CheckBox.font", uiFont);
        UIManager.put("RadioButton.font", uiFont);
        UIManager.put("ComboBox.font", uiFont);
        UIManager.put("TextField.font", uiFont);
        UIManager.put("TextArea.font", uiFont);
        UIManager.put("Table.font", uiFont);
        UIManager.put("TabbedPane.font", uiFont);

        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        subjectConfigPanel1stSem = new SubjectConfigPanel();    
        subjectConfigPanel2ndSem = new SubjectConfigPanel1();   

        autoSchedulePanel = new AutoSchedulePanel(new java.util.ArrayList<LabSchedule>());

        subjectConfigPanel1stSem.setAutoSchedulePanel(autoSchedulePanel);
        subjectConfigPanel2ndSem.setAutoSchedulePanel(autoSchedulePanel);

        mainTabs.addTab("Dashboard", new DashboardPanel());
        mainTabs.addTab("Subject Config 1st Sem", subjectConfigPanel1stSem);
        mainTabs.addTab("Subject Config 2nd Sem", subjectConfigPanel2ndSem);

        mainTabs.addChangeListener(e -> {
            int selectedIndex = mainTabs.getSelectedIndex();
            String title = mainTabs.getTitleAt(selectedIndex);

            if (title.equals("Auto Schedule")) {
                // Optional: Refresh schedule when tab is opened
                subjectConfigPanel1stSem.generateSchedules(); 
                List<LabSchedule> updatedSchedules = subjectConfigPanel1stSem.getFinalSchedules();
                autoSchedulePanel.reloadSchedules(updatedSchedules);
            }
        });

        subjectConfigPanel1stSem.getGenerateButton().addActionListener(e -> {
            subjectConfigPanel1stSem.generateSchedules();
            autoSchedulePanel.reloadSchedules(subjectConfigPanel1stSem.getFinalSchedules());

            if (mainTabs.indexOfComponent(autoSchedulePanel) == -1) {
                mainTabs.addTab("Auto Schedule", autoSchedulePanel);
            }

            mainTabs.setSelectedComponent(autoSchedulePanel);
        });


        subjectConfigPanel2ndSem.getGenerateButton().addActionListener(e -> {
            subjectConfigPanel2ndSem.generateSchedules();
            autoSchedulePanel.reloadSchedules(subjectConfigPanel2ndSem.getFinalSchedules());

            if (mainTabs.indexOfComponent(autoSchedulePanel) == -1) {
                mainTabs.addTab("Auto Schedule", autoSchedulePanel);
            }

            mainTabs.setSelectedComponent(autoSchedulePanel);
        });

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        mainTabs = new javax.swing.JTabbedPane();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ASC MO Automatic Scheduler");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(mainTabs);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
try {
    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    System.out.println(info.getName());
}
    
} catch (Exception e) {
    e.printStackTrace();
}

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame();            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTabbedPane mainTabs;
    // End of variables declaration//GEN-END:variables
}
